version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [release, dry_nexus_staging, nexus_staging, cicd_test, blank]
    default: blank
  gio_product_version:
    type: string
    default: "78.15.42"
orbs:
  secrethub: secrethub/cli@1.0.0
  gravitee: gravitee-io/gravitee@dev:1.0.4
jobs:
  # empty_job:
    # docker:
     # - image: alpine
    # resource_class: small
    # working_directory: /mnt/ramdisk
    # steps:
      # - run:
          # name: "This is a dummy empty job (isn't it ?)"
          # command: echo "No task is executed."
  cicd_test_job:
    docker:
     - image: 'cimg/base:stable'
    resource_class: medium
    # working_directory: /mnt/ramdisk
    environment:
      GIO_PRODUCT_VERSION: << pipeline.parameters.gio_product_version >>
      RELEASE_REPO: git@github.com:gravitee-lab/release-with-nexus-staging-test1
      SECRETHUB_ORG: gravitee-lab
      SECRETHUB_REPO: cicd
      GIT_SSH_PUB_KEY: 'secrethub://gravitee-lab/cicd/graviteebot/git/ssh/public_key'
      GIT_SSH_PRV_KEY: 'secrethub://gravitee-lab/cicd/graviteebot/git/ssh/private_key'
    steps:
      # secrethub cannot be installed directly into a docker image
      # So git_config orb cannot be used as is into a docker container.
      #
      # - secrethub/install
      # - gravitee/git_config:
          # secrethub_org: $SECRETHUB_ORG
          # secrethub_repo: $SECRETHUB_REPO
      - secrethub/exec:
          command: |
                    mkdir -p /tmp/graviteebot/.secrets/.ssh.gravitee.io
                    echo $GIT_SSH_PUB_KEY > /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa.pub
                    echo $GIT_SSH_PRV_KEY > /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    ssh-keygen -R github.com
                    mkdir -p ~/.ssh
                    touch ~/.ssh/known_hosts
                    chmod 700 -R ~/.ssh/
                    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                    chmod 700 /tmp/graviteebot/.secrets/.ssh.gravitee.io
                    chmod 644 /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa.pub
                    chmod 600 /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    ssh-add -D
                    # cat /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    # ssh-add /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    ssh -Ti /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa git@github.com || true
                    exit 0
      - run:
          name: "This is a dummy empty job (isn't it ?)"
          command: |
                    echo "value of GIO_PRODUCT_VERSION = [$GIO_PRODUCT_VERSION]"
                    echo "value of GIO_PRODUCT_VERSION = [${GIO_PRODUCT_VERSION}]"
                    echo "value of RELEASE_REPO = [${RELEASE_REPO}]"
                    echo "value of SECRETHUB_ORG = [${SECRETHUB_ORG}]"
                    echo "value of SECRETHUB_REPO = [${SECRETHUB_REPO}]"
                    # export OPS_HOME=$(pwd)
                    # echo "Current diectory: [$(pwd)]"
                    # git clone ${RELEASE_REPO} ${HOME}/retrieved-release-repo
                    # export LOCAL_RELEASE_REPO=${HOME}/retrieved-release-repo
      - persist_to_workspace:
          root: /tmp
          paths:
            - graviteebot

  cicd_test_job2:
    docker:
     - image: 'cimg/base:stable'
    resource_class: medium
    # working_directory: /mnt/ramdisk
    environment:
      GIO_PRODUCT_VERSION: << pipeline.parameters.gio_product_version >>
      RELEASE_REPO: git@github.com:gravitee-lab/release-with-nexus-staging-test1
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Git SSH config"
          command: |
                    # mkdir -p /tmp/graviteebot/.secrets/.ssh.gravitee.io
                    # echo $GIT_SSH_PUB_KEY > /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa.pub
                    # echo $GIT_SSH_PRV_KEY > /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    echo "check [/tmp]"
                    ls -allh /tmp
                    echo "check [/tmp/graviteebot]"
                    ls -allh /tmp/graviteebot
                    echo "check [/tmp/graviteebot/.secrets/.ssh.gravitee.io]"
                    ls -allh /tmp/graviteebot/.secrets/.ssh.gravitee.io
                    # --
                    mkdir -p ~/.ssh
                    chmod 700 ~/.ssh
                    touch ~/.ssh/known_hosts
                    ssh-keygen -R github.com
                    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                    chmod 700 /tmp/graviteebot/.secrets/.ssh.gravitee.io
                    chmod 644 /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa.pub
                    chmod 600 /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    ssh-add -D
                    # cat /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    # ssh-add /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa
                    ssh -Ti /tmp/graviteebot/.secrets/.ssh.gravitee.io/id_rsa git@github.com || true


      - run:
          name: "This is a dummy empty job (isn't it ?)"
          command: |
                    echo "value of GIO_PRODUCT_VERSION = [$GIO_PRODUCT_VERSION]"
                    echo "value of GIO_PRODUCT_VERSION = [${GIO_PRODUCT_VERSION}]"
                    echo "value of RELEASE_REPO = [${RELEASE_REPO}]"
                    echo "value of SECRETHUB_ORG = [${SECRETHUB_ORG}]"
                    echo "value of SECRETHUB_REPO = [${SECRETHUB_REPO}]"
                    export OPS_HOME=$(pwd)
                    echo "Current diectory: [$(pwd)]"
                    git clone ${RELEASE_REPO} ${HOME}/retrieved-release-repo
                    export LOCAL_RELEASE_REPO=${HOME}/retrieved-release-repo


  dry_run_orchestrator:
    machine:
      image: 'ubuntu-1604:201903-01'
    environment:
      GITHUB_ORG: ${GITHUB_ORG}
      GIO_PRODUCT_VERSION: << pipeline.parameters.gio_product_version >>
      RELEASE_REPO: git@github.com:gravitee-lab/release-with-nexus-staging-test1
      SECRETHUB_ORG: gravitee-lab
      SECRETHUB_REPO: cicd
    steps:
      - checkout
      - secrethub/install
      # - secrethub/install
      - gravitee/git_config:
          secrethub_org: gravitee-lab
          secrethub_repo: cicd
      - run:
          name: "Test Git config"
          command: |
                    echo "check [${HOME}/.ssh.gravitee.io/]"
                    ls -allh ${HOME}/.ssh.gravitee.io/
                    echo "check [${HOME}/.ssh.gravitee.io/id_rsa]"
                    ls -allh ${HOME}/.ssh.gravitee.io/id_rsa
                    echo "check [${HOME}/.ssh.gravitee.io/id_rsa.pub]"
                    ls -allh ${HOME}/.ssh.gravitee.io/id_rsa.pub
                    git config --list
                    ssh -Ti ~/.ssh.gravitee.io/id_rsa git@github.com || true
      - run:
          name: "Retrieving Release.json"
          command: |
                    export OPS_HOME=$(pwd)
                    echo "Current diectory: [$(pwd)]"
                    export LOCAL_RELEASE_REPO=$(mktemp -d -t "s3cmd_install_ops-XXXXXXXXXX")
                    git clone ${RELEASE_REPO} ${LOCAL_RELEASE_REPO}
                    cd ${LOCAL_RELEASE_REPO}
                    git checkout ${GIO_PRODUCT_VERSION}
                    cp -f ${LOCAL_RELEASE_REPO}/release.json ${OPS_HOME}/release.json
                    cd ${OPS_HOME}
      - run:
          name: "Docker pull"
          command: |
                    docker pull quay.io/gravitee-lab/cicd-orchestrator:stable-latest
      - run:
          name: "Running the Gio CICD Orchestrator as docker container"
          command: |
                    echo "Checking pipeline env. : "
                    ls -allh
                    export GITHUB_ORG=gravitee-lab
                    export SECRETHUB_ORG=gravitee-lab
                    export SECRETHUB_REPO=cicd
                    export MAVEN_PROFILE_ID='gravitee-release'
                    echo "GITHUB_ORG=${GITHUB_ORG}"
                    echo "SECRETHUB_ORG=${SECRETHUB_ORG}"
                    echo "SECRETHUB_REPO=${SECRETHUB_REPO}"
                    echo "MAVEN_PROFILE_ID=${MAVEN_PROFILE_ID}"
                    # checking docker image pulled in previous step is there
                    docker images
                    # --> .secrets.json is used by Gravitee CI CD Orchestrator to authenticate to Circle CI
                    CCI_SECRET_FILE=$PWD/.secrets.json
                    secrethub read --out-file ${CCI_SECRET_FILE} ${SECRETHUB_ORG}/${SECRETHUB_REPO}/graviteebot/circleci/api/.secret.json
                    secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/graviteebot/circleci/secrethub-svc-account/token > ./.secrethub.credential
                    ls -allh ${CCI_SECRET_FILE}
                    # Docker volumes to map pipeline checked out git tree, .env file and .secrets.json files inside the docker container
                    # export DOCKER_VOLUMES="-v $PWD:/graviteeio/cicd/pipeline -v $PWD/.env:/graviteeio/cicd/.env -v $PWD/.secrets.json:/graviteeio/cicd/.secrets.json"
                    export DOCKER_VOLUMES="-v $PWD:/graviteeio/cicd/pipeline -v $PWD/.secrets.json:/graviteeio/cicd/.secrets.json -v $PWD/.secrethub.credential:/graviteeio/cicd/.secrethub.credential"
                    export ENV_VARS="--env GH_ORG=${GITHUB_ORG} --env SECRETHUB_ORG=${SECRETHUB_ORG} --env SECRETHUB_REPO=${SECRETHUB_REPO} --env MAVEN_PROFILE_ID=${MAVEN_PROFILE_ID}"
                    docker run --name orchestrator ${ENV_VARS} ${DOCKER_VOLUMES} --restart no -it quay.io/gravitee-lab/cicd-orchestrator:stable-latest -s mvn_nexus_staging --dry-run
                    exit "$?"
  run_orchestrator:
    machine:
      image: 'ubuntu-1604:201903-01'
    environment:
      GITHUB_ORG: ${GITHUB_ORG}
      SECRETHUB_ORG: gravitee-lab
      SECRETHUB_REPO: cicd
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "Docker pull"
          command: |
                    docker pull quay.io/gravitee-lab/cicd-orchestrator:stable-latest
      - run:
          name: "Running the Gio CICD Orchestrator as docker container"
          command: |
                    echo "Checking pipeline env. : "
                    ls -allh
                    export GITHUB_ORG=gravitee-lab
                    export SECRETHUB_ORG=gravitee-lab
                    export SECRETHUB_REPO=cicd
                    export MAVEN_PROFILE_ID='gravitee-release'
                    echo "GITHUB_ORG=${GITHUB_ORG}"
                    echo "SECRETHUB_ORG=${SECRETHUB_ORG}"
                    echo "SECRETHUB_REPO=${SECRETHUB_REPO}"
                    echo "MAVEN_PROFILE_ID=${MAVEN_PROFILE_ID}"
                    # checking docker image pulled in previous step is there
                    docker images
                    # --> .secrets.json is used by Gravitee CI CD Orchestrator to authenticate to Circle CI
                    CCI_SECRET_FILE=$PWD/.secrets.json
                    secrethub read --out-file ${CCI_SECRET_FILE} ${SECRETHUB_ORG}/${SECRETHUB_REPO}/graviteebot/circleci/api/.secret.json
                    secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/graviteebot/circleci/secrethub-svc-account/token > ./.secrethub.credential
                    ls -allh ${CCI_SECRET_FILE}
                    # Docker volumes to map pipeline checked out git tree, .env file and .secrets.json files inside the docker container
                    # export DOCKER_VOLUMES="-v $PWD:/graviteeio/cicd/pipeline -v $PWD/.env:/graviteeio/cicd/.env -v $PWD/.secrets.json:/graviteeio/cicd/.secrets.json"
                    export DOCKER_VOLUMES="-v $PWD:/graviteeio/cicd/pipeline -v $PWD/.secrets.json:/graviteeio/cicd/.secrets.json -v $PWD/.secrethub.credential:/graviteeio/cicd/.secrethub.credential"
                    export ENV_VARS="--env GH_ORG=${GITHUB_ORG} --env SECRETHUB_ORG=${SECRETHUB_ORG} --env SECRETHUB_REPO=${SECRETHUB_REPO} --env MAVEN_PROFILE_ID=${MAVEN_PROFILE_ID}"
                    docker run --name orchestrator ${ENV_VARS} ${DOCKER_VOLUMES} --restart no -it quay.io/gravitee-lab/cicd-orchestrator:stable-latest -s mvn_nexus_staging --dry-run false
                    exit "$?"
workflows:
  version: 2.1
  # Blank process invoked when pull requests events are triggered
  # blank:
    # when:
      # equal: [ blank, << pipeline.parameters.gio_action >> ]
    # jobs:
      # - empty_job:
          # context: cicd-orchestrator
  # Release Process DRY RUN
  cicd_test_wf:
    when:
      equal: [ cicd_test, << pipeline.parameters.gio_action >> ]
    jobs:
      - cicd_test_job:
          context: cicd-orchestrator
      - cicd_test_job2:
          requires:
            - cicd_test_job
          context: cicd-orchestrator
  dry_nexus_staging_process:
    when:
      equal: [ dry_nexus_staging, << pipeline.parameters.gio_action >> ]
    jobs:
      - dry_run_orchestrator:
          context: cicd-orchestrator
          filters:
            tags:
              only:
                - /^[0-9]+.[0-9]+.[0-9]+/
  nexus_staging_process:
    when:
      equal: [ nexus_staging, << pipeline.parameters.gio_action >> ]
    jobs:
      - run_orchestrator:
          context: cicd-orchestrator
          # one cannot filters branches when conditonal workflows ?
          filters:
            branches:
              # ---
              # Will run only when git commits are pushed to master branch
              # Therefore, will be triggered when a pull request is accepted, with target branch being
              # the master branch.
              only:
                - /^[0-9]+.[0-9]+.x/
                - master # ? as discussed ? if un-commented, any new pushed commit to master will trigger a Release Process DRY RUN
